### ISSUE TITLE
Modify label.py to handle multiple people performing the labeling

### ISSUE THREAD

**Issue by marco-c** [marco-c/autowebcompat#21]
Modify the label.py script to handle multiple people performing the labeling (I would suggest simply adding a parameter PERSON, and writing a labels_PERSON.csv according to this parameter). Then, write another script that generates labels.csv from all the labels_*.csv files (basically storing the lines from labels_*.csv which agree on the label).

**Comment by sagarvijaygupta** [comment]
@marco-c Is it necessary to have different files for different persons? Like one person starts labeling images and has labeled 100 of them and then leaves, then we will create a file with these labels. Next day he again starts but the file name is not saved so he will have to start from start. Should I add a '''name_text_box''' in the start so that person is able to enter the name or select the file from drop down menu if he wants to append results to it?

**Comment by marco-c** [comment]
The person should be able to specify who they are by passing a "--person" option to label.py. The files will be named "labels_PERSON.csv", so they will be able to append results to it.

**Comment by SkullTech** [comment]
@sagarvijaygupta are you working on this?

**Comment by sagarvijaygupta** [comment]
@SkullTech Yes! I am on it.
